version: '3.7'
services:
  cassandra:
    image: sapvs/cassandra-alpine:3.0.25-8
    expose:
      - "7199"
      - "7000"
      - "7001"
      - "9042"
      - "9160"
    env_file:
      - cassandra.env
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 1
