name: ci

on:
  push:
    branches:
      - 'master'
    paths:
      - Dockerfile
jobs:
  docker1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        openjre_ver: [8-latest]
        cassandra_ver: [3.0.25, 3.11.11, 4.0.1]
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: get-id
        run: |
          id=$(echo ${{ matrix.openjre_ver }} | cut -d- -f1)
          echo "::set-output name=id::$id"
      - run: echo "${{ steps.get-id.outputs.id }}"
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: | 
            OPENJRE_VERSION=${{ matrix.openjre_ver }}
            CASSANDRA_VERSION=${{ matrix.cassandra_ver }}
          push: true
          tags: sapvs/cassandra-alpine:${{ matrix.cassandra_ver }}-${{ steps.get-id.outputs.id }}
  docker2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        openjre_ver: [11-latest, 17-latest]
        cassandra_ver: [4.0.1]
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: get-id
        run: |
          id=$(echo ${{ matrix.openjre_ver }} | cut -d- -f1)
          echo "::set-output name=id::$id"
      - run: echo "${{ steps.get-id.outputs.id }}"
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: | 
            OPENJRE_VERSION=${{ matrix.openjre_ver }}
            CASSANDRA_VERSION=${{ matrix.cassandra_ver }}
          push: true
          tags: sapvs/cassandra-alpine:${{ matrix.cassandra_ver }}-${{ steps.get-id.outputs.id }}
